#https://stackoverflow.com/questions/65844033/conditional-needs-in-github-action

name: "Conditional dependency"

on:
  workflow_dispatch:


jobs:
  build1:
    runs-on: windows-latest
    steps:
      - name: Cond1
        run: |
          if (  "1".equals("2") ){
          echo "true condition"
          }
          else {
          echo "false condition"
          }
       

  test:
    runs-on: windows-latest
    needs: [build1]

    steps:
      - run: echo "build"

  deploy:
    runs-on: windows-latest
    needs: [test]

    steps:
      - run: echo "deploy"
