#https://stackoverflow.com/questions/65844033/conditional-needs-in-github-action

name: "Conditional dependency"

on:
  workflow_dispatch:

env:
  branch: ${{ github.ref }}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Cond1
        run: |
        if: false
         echo "false condition"
         
      - name: cond2
        run: |
        if: true
          echo "true condition"
         
       

  test:
    runs-on: windows-latest
    needs: build

    steps:
      - run: echo "build"

  deploy:
    runs-on: windows-latest


    steps:
      - run: echo "deploy"
