#https://stackoverflow.com/questions/65844033/conditional-needs-in-github-action

name: "Conditional dependency"

on:
  workflow_dispatch:


jobs:
  build1:
    if: ${{ "1".equals("1") }}
    uses: atlassian-natchiar/emptyrepo/.github/workflows/main.yml@main
        
  test:
    runs-on: windows-latest
    needs: [build1]

    steps:
      - run: echo "build"

  deploy:
    runs-on: windows-latest
    needs: [test]

    steps:
      - run: echo "deploy"
