name: manual job trigger workflow 

on:
  workflow_dispatch:

jobs:
  job1:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.sha }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Hello world
        run: echo "execitededdeded"
        
  staging: 
    name: Deploy to staging
    needs: job1
    runs-on: ubuntu-latest
    environment:
      name: staging 

    steps:
    # Deploy to App Service Linux
      - name: Deploy to Azure WebApp
        id: deploy_staging
        uses: actions/checkout@v2
        with:
          slot-name: staging

    
