name: manual job trigger workflow 

on:
  workflow_dispatch:

jobs:
  build_with_test:
    name: build
    runs-on: windows-latest
    outputs:
      output_filename: ${{ steps.output_filename_generation.outputs.artifactname}}

    steps:

      - name: Hello world
        run: echo "execitededdeded"
        
      - name: Output File name
        id: output_filename_generation
        run: |
          $tagvar="SourceTreeReleaseArchive_${{ github.sha }}.zip"
          echo "::set-output name=artifactname::$tagvar"
        
  deploy_to_beta: 
    name: Deploy for Beta
    needs: build_with_test
    runs-on: windows-latest
    environment:
      name: staging 

    steps:
    # Deploy to App Service Linux
      - name: Deploy to s3
        id: deploy_beta
#        uses: actions/checkout@v2
#        with:
#          slot-name: staging
        run: |
          echo ${{needs.build_with_test.outputs.output_filename}}
          
  ga_release: 
    name: Deploy for GA
    needs: deploy_to_beta
    runs-on: windows-latest
    environment:
      name: staging 
    steps:
      - name: Deploy GA to s3
        id: deploy_ga
        
        run: |
          echo "Ga build"
          echo ${{needs.build_with_test.outputs.output_filename}}
      

    
