name: manual job trigger workflow 

on:
  workflow_dispatch:

jobs:
  job1:
    name: build
    runs-on: windows-latest
    outputs:
      output_filename: ${{ steps.output_filename_generation.outputs.artifactname}}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.sha }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Hello world
        run: echo "execitededdeded"
        
      - name: Output File name
        id: output_filename_generation
        run: |
          $tagvar="SourceTreeReleaseArchive_${{ github.sha }}.zip"
          echo "::set-output name=artifactname::$tagvar"
        
  staging: 
    name: Deploy to staging
    needs: job1
    runs-on: windows-latest
    environment:
      name: staging 

    steps:
    # Deploy to App Service Linux
      - name: Deploy to Azure WebApp
        id: deploy_staging
#        uses: actions/checkout@v2
#        with:
#          slot-name: staging
        run: |
          echo ${{needs.Package_prep.outputs.output_filename}}

    
