name: manual job trigger workflow 

on:
  workflow_dispatch:
   inputs:
    releasePercentage:
      description: Rollout Percentage
      required: true
    releaseMode:
        type: string
        description: ga beta 
        required: true

jobs:
  build_with_test:
    name: build
    runs-on: windows-latest
    outputs:
      output_filename: ${{ steps.output_filename_generation.outputs.artifactname}}

    steps:

      - name: Hello world
        run: echo "execitededdeded"
        
      - name: Output File name
        id: output_filename_generation
        run: |
          $tagvar="SourceTreeReleaseArchive_${{ github.sha }}.zip"
          echo "::set-output name=artifactname::$tagvar"
        
  deploy_to_beta: 
    name: Deploy for Beta
    needs: build_with_test
    runs-on: windows-latest
    environment:
      name: staging 

    steps:
    # Deploy to App Service Linux
      - name: Deploy to s3
        id: deploy_beta
#        uses: actions/checkout@v2
#        with:
#          slot-name: staging
        run: |
          $mode_of_release="${{ github.event.inputs.releaseMode}}"
          if ( %$mode_of_release% == "beta")
          {
          echo "Beta Release"
          echo ${{needs.build_with_test.outputs.output_filename}}
          }
          else
          {
          echo "Skipping Beta Release"
          }
          
  ga_release: 
    name: Deploy for GA
    needs: [build_with_test,deploy_to_beta]
    runs-on: windows-latest
    environment:
      name: staging 
    steps:
      - name: Deploy GA to s3
        id: deploy_ga
        
        run: |
          echo "Ga build"
          echo ${{needs.build_with_test.outputs.output_filename}}
          echo "Release percentage" ${{ github.event.inputs.releasePercentage}}
      

    
